# Hexo Configuration Hexo配置文件
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/


# 网站信息
#标题
title: 猪猪娱乐
#副标题
subtitle: 做自己爱做的事，爱自己在做的事！
#网站描述
description: 每个人都可以活的很有价值！
#作者昵称
author: zhuzhuxia
#网站语言，默认英语，设置简体汉语
language: zh-Hans
#时区，默认电脑时区
timezone: Asia/Shanghai


# 网址设置
#如果网站是放在子目录中，将url设置成'http://yoursite.com/child'，将root设置成'/child/'
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
#网址
url: zhuzhuyule.xyz
#网站根目录。如果网站是放在子目录中，将root设置成'子目录名'
root: /
#文章链接地址格式 。即文章存放的目录。
permalink: :year/:month/:day/:title/
permalink_defaults:


# 目录设置
#资源文件夹，放在里面的文件会上传到github中
source_dir: source
#公共文件夹，存放生成的静态文件
public_dir: _Web
#标签文件夹，默认是tags。实际存放在source/tags中。
tag_dir: tags
rss_dir: rss
#档案文件夹，默认是archives。
archive_dir: archives
#分类文件夹，默认是categories。实际存放在source/categories中。
category_dir: categories
#代码文件夹，默认是downloads/code
code_dir: downloads/code
#国际化文件夹，默认跟language相同
i18n_dir: :lang
#不需要渲染的文件夹或文件夹,放在[]中
# 这两个文件是百度和google的站长验证文件，不能渲染，否则会改变内容，不能验证过
skip_render: [xxxxxxxxxxxxxxxx.html, xxxxxxxxxxxxxxx.html, xxxxxxxxxxxxxxx.html, 
                xxxxxxxxxxxxxxxxxx.html, README.md, 模板.md, robots.txt,
                test.html,test.css,test.js,404.html,CNAME]


# 写作选项
# 新建博文（帖子）的默认名称
# File name of new posts
new_post_name: :title.md 
#默认布局模板是post，而不是draft和page
default_layout: post
#是否将标题转换成标题形式（首字母大写）
titlecase: true # Transform title into titlecase
#在新标签页面中打开网页
external_link: true # Open external links in new tab
filename_case: 0
#是否渲染草稿
render_drafts: false
#启动 Asset 文件夹
post_asset_folder: false
#把链接改为与根目录的相对位址
relative_link: false
#显示未来的文章
future: true
#代码块的设置
highlight:
  enable: true      # 使用代码高亮
  line_number: true # 显示行号
  auto_detect: false # 自动检测语言
  tab_replace: '  '


# 分类和标签
# 默认分类
default_category: uncategorized
#分类别名
category_map: 
#标签别名
tag_map: 

# maxdepth: Use headings whose depth is at most maxdepth.
# class: The CSS Class for the toc. (Default is false)
# slugify: Choose which slugify function you want to use. Currently support uslug (Default) and transliteration.
# anchor: Whether should have an anchor for each headings. (Default is false)
#   position: Where should the anchor be, before the title, or after the title. (Default is after);
#   symbol: Which symbol you want the anchor be. (Default is #);
#   style: The CSS class for the anchor, (Default is header-anchor);
toc:
  maxdepth: 5
  class: toc
  slugify: transliteration
  anchor:
    position: after
    symbol: '#'
    style: header-anchor

# 日期和时间格式
#Hexo 使用 Moment.js 来解析和显示时间。
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss


# 分页配置
# ---------------下面选项需要对应插件的支持---------------
# npm install hexo-generator-archive --save
# npm install hexo-generator-category --save
# npm install hexo-generator-tag --save
## Set per_page to 0 to disable pagination
#每页显示的文章量 
#per_page: 10


# npm install hexo-generator-index --save
#首页的分页设置
index_generator:
  per_page: 15
  #order_by: -date
  #include: # 具有该属性的文章 首页*显示*
    # - category 文章分类
    # - tag 文章标签
    # - path _post/ # 文章源路径
    # - category Skill
  exclude: # 具有该属性的文章 首页不展示
    # - category 文章分类
    # - tag 文章标签
    - path _drafts/ # 文章源路径
    - path _posts/nodes/ # 文章源路径

    
#  ./node_modules_modify/hexo-generator-indexMe 文件夹到  ./node_moduls/ 目录下
#自定义的分页设置
indexMe_generator:
  pagename: nodes
  per_page: 15
  order_by: -date
  include: # 具有该属性的文章 首页*显示*
    # - category 文章分类
    # - tag 文章标签
    - path _drafts/ # 文章源路径
    - path _posts/nodes/ # 文章源路径
    # - category Skill

#归档页的分页设置
archive_generator:
  per_page: 30
  yearly: true
  monthly: true
#标签页的分页设置
tag_generator:
  per_page: 20

#分页路径，在public中可以看到
pagination_dir: page

# Extensions 拓展插件配置
## Plugins: https://hexo.io/plugins/
plugins: 

# Sitemap Setting
sitemap:
 path: sitemap.xml
 
baidusitemap:
 path: baidusitemap.xml

# 配置RSS
feed: 
  #feed 类型 (atom/rss2)
  type: atom   
  #rss 路径
  path: atom.xml  
  #在 rss 中最多生成的文章数(0显示所有)
  limit: 0

# 自定义站点内容搜索
# 需要先安装插件：
# npm install hexo-generator-searchdb --save
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# 主题配置
## Themes: https://hexo.io/themes/
#theme: false #禁用主题
#theme: landscape
theme: next

#zhuzhuyule.xyz
baidu_analytics: xxxxxxxxxxxxxxxxx
#zhuzhuyule.coding.me
#baidu_analytics: xxxxxxxxxxxxxxx
#zhuzhuyule.github.io
#baidu_analytics: xxxxxxxxxxxxx
google_analytics: xxxxxxxxxxxx
google_site_verification: xxxxxxxxxxxxxxxxxxxxxxxxxx

leancloud_visitors:
  enable: true
  app_id: xxxxxxxxxxxxxx-xxxxxxxxx
  app_key: xxxxxxxxxxxxxxx

# 百度分享服务
baidushare: true
 
# 部署配置
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: 
    # 部署到coding.net。取消注释，可同时部署
    coding: https://git.coding.net/zhuzhuyule/zhuzhuyule.coding.me.git,master
    # 部署到github
    github: https://github.com/zhuzhuyule/zhuzhuyule.github.io.git,master    
  #type: baidu_url_submitter
